image: $IMAGE_NAME

cache:
  paths:
    - cache/

before_script:
  - echo cache >>.Rbuildignore
  - >
    echo >~/.Rprofile '
      local({
        cores <- parallel::detectCores()
        options(Ncpus = cores)
      })'

stages:
  - setup
  - test
  - build

setup:
  stage: setup
  script:
    - mkdir -p cache
    - R_LIBS_USER="$PWD/cache" Rscript -e 'devtools::install_deps(".", TRUE)'

check:
  stage: test
  script:
    - R_LIBS_USER="$PWD/cache" Rscript -e 'devtools::check(".")'

build:
  stage: build
  artifacts:
    expire_in: 1 year
    paths:
      - graphite_*.tar.gz
  script:
    - R_LIBS_USER="$PWD/cache" Rscript -e 'devtools::build(".", dest_path = ".")'
